# Resumen del curso {.unnumbered}

::: {.callout-note}
Este tutorial es una traducción realizada por el [Grupo de Biología
Computacional](https://biologia-computacional.github.io/) de la Universidad
de Antioquia. Encuentra el tutorial original [en este
enlace](https://www.ebi.ac.uk/training/online/courses/bioinformatics-terrified/).
:::

## Descripción del curso

### ¿Para quién es este curso?

Este curso está dirigido a investigadores experimentales o de laboratorio
que trabajan en las ciencias biológicas moleculares y que tienen poca o
ninguna experiencia previa en el uso de bases de datos o herramientas
bioinformáticas. Este curso proporcionará una visión general amplia de la
bioinformática como área de estudio y los recursos disponibles públicamente
a los que los investigadores pueden acceder y utilizar.

Sería una ventaja tener conocimiento a nivel de pregrado de un área
relacionada a las ciencias de la vida.

Este tutorial es parte de
[Introductory bioinformatics pathway: A curated set of EMBL-EBI online
courses](https://www.ebi.ac.uk/training/online/courses/introductory-bioinformatics-pathway/),
el cual provee una introducción a la bioinformática, una breve guía a los
recursos disponibles en el EMBL-EBI y más detalles sobre algunos de esos
recursos, incluyendo Ensembl, UniProt y Expression Atlas.

### ¿Qué lograré?

Al finalizar este curso podrás:

- Evaluar el papel de la bioinformática en las ciencias moleculares.
- Describir las características principales de las bases de datos primarias
  y secundarias.
- Listar las estrategias para describir los datos de manera consistente.
- Identificar algunos de los diferentes tipos de análisis de datos que se
  pueden aplicar para resolver problemas biológicos.

### ¿Qué recursos necesito?

No se requieren recursos específicos para completar este curso.
