### ¿Para quién es la bioinformática?

![**Figura 2.** Las personas (ficticias) ilustradas aquí, mientras que no son
bioinformáticos en el sentido clásico, usan bioinformática para su
investigación. Caricaturas cortesía de Jenny Cham, EMBL-EBI.](https://www.ebi.ac.uk/training/online/courses/bioinformatics-terrified/wp-content/uploads/sites/4/2019/09/bx_terrified_fig_2_700px-1.jpg)

Las ciencias moleculares de la vida se han vuelto cada vez más impulsadas
por los datos y dependientes del intercambio de datos a través de bases de
datos de acceso abierto [@marx2013]. Esto es tan cierto para las ciencias
aplicadas como para la investigación fundamental. Además, no es necesario
ser un bioinformático para usar las bases de datos, métodos y herramientas
biológicas. Sin embargo, a medida que la generación de grandes conjuntos de
datos se vuelve más y más central para la investigación biomédica, se vuelve
más necesario para cada científico molecular de la vida entender qué se
puede (y, muy importante, qué no se puede) lograr usando la bioinformática,
y ser capaz de trabajar con expertos en bioinformática para diseñar,
analizar e interpretar sus experimentos (Figura 2).
