# ¿Qué es la bioinformática?

Puesto de manera simple, la bioinformática es la ciencia de almacenar,
obtener y analizar grandes cantidades de información biológica. Es un área
altamente interdisciplinaria que involucra muchos tipos de especialistas,
incluyendo biólogos, científicos moleculares de la vida, científicos de la
computación y matemáticos.

El término bioinformática fue acuñado por Paulien Hogeweg y Ben Hesper para
describir "el estudio de los procesos informáticos en los sistemas bióticos"
y encontró un uso temprano cuando los primeros datos de secuencias
biológicas comenzaron a ser compartidos. Mientras que los primeros métodos
de análisis son todavía fundamentales para muchos experimentos a gran
escala en las ciencias moleculares de la vida, hoy en día la bioinformática
se considera una disciplina mucho más amplia, que abarca el modelamiento y
el análisis de imágenes adicionalmente a los métodos clásicos usados para la
comparación de secuencias lineales o estructuras tridimensionales (Figura
1).

![**Figura 1.** Un amplio panorama de los diferentes tipos de datos que
hacen parte del área de la bioinformática. Tradicionalmente, la
bioinformática fue usada para describir la ciencia de almacenar y analizar
datos de secuencias de biomoléculas, pero el término es usado hoy en día de
una manera más amplia, abarcando la biología estructural computacional, la
biología química y la biología de sistemas (tanto la integración de datos
como el modelamiento de sistemas).](figs/fig_1.svg)

## Distinción de la informática médica

La bioinformática es distinta de la **informática médica**: el estudio
interdisciplinario del diseño, desarrollo, adopción y aplicación de
innovaciones basadas en las tecnologías de la información en la prestación,
gestión y planificación de servicios de **atención médica**. En algún lugar
en medio de las dos disciplinas se encuentra la **informática biomédica**:
el área interdisciplinaria que estudia y busca el uso efectivo de **datos
biomédicos**, información y conocimiento para la investigación científica,
la resolución de problemas y la toma de decisiones, motivados por los
esfuerzos por mejorar la salud humana.

Proyectos iniciados recientemente, como el [Proyecto 100.000
genomas](https://www.genomicsengland.co.uk/the-100000-genomes-project/#),
están cerrando las brechas entre estas disciplinas, pero de manera general
la bioinformática trata con datos de investigaciones y los usa para
propósitos de investigación, la informática médica trata con datos de
pacientes individuales para propósitos de gestión clínica (diagnóstico,
tratamiento, prevención...) y la informática biomédica intenta hacer un
puente entre estos extremos.
